#!/tool/pandora64/bin/python

import re

def main(strings):
   code = 0
   chars = 0
   codeTotal = 0
   charsTotal = 0
   for string in strings:
      code = len(string[0])+2
      chars = len(string[1])
      codeTotal += code
      charsTotal += chars
      #print "String: '{}'\t'{}'\n\tCode: '{}'\n\tChar: '{}'".format( string[0], string[1], code, chars )
   print "Result: {}".format(codeTotal - charsTotal)

def main2(strings):
   code = 0
   chars = 0
   codeTotal = 0
   charsTotal = 0
   print "UNFINISHED"
   for string in strings:
      newString = repr(string[0])
      code = len(repr(newString))+2
      chars = len(string[1])
      codeTotal += code
      charsTotal += chars
      #print "String: '{}'\t'{}'\n\tCode: '{}'\n\tChar: '{}'".format( newString, string[1], code, chars )
   print "Result: {}".format(codeTotal - charsTotal)

inputString = [
[r"\xa8br\x8bjr\"", "\xa8br\x8bjr\""],
[r"nq", "nq"],
[r"zjrfcpbktjmrzgsz\xcaqsc\x03n\"huqab", "zjrfcpbktjmrzgsz\xcaqsc\x03n\"huqab"],
[r"daz\\zyyxddpwk", "daz\\zyyxddpwk"],
[r"draes\xa2n\\g\x27ek\"lj\"\\viqych", "draes\xa2n\\g\x27ek\"lj\"\\viqych"],
[r"nnx\\krnrfomdnt\x2flbl\xd2xpo\"cp\"k", "nnx\\krnrfomdnt\x2flbl\xd2xpo\"cp\"k"],
[r"kwdaapalq", "kwdaapalq"],
[r"u\"ptk", "u\"ptk"],
[r"ckhorczuiudfjmmcc\\u\"wozqxibsfjma", "ckhorczuiudfjmmcc\\u\"wozqxibsfjma"],
[r"ydctdrxat\"pd\"lwi\"bjesevfw\xe8", "ydctdrxat\"pd\"lwi\"bjesevfw\xe8"],
[r"v\"\xa8rrzep\"\"r", "v\"\xa8rrzep\"\"r"],
[r"nbydghkfvmq\\\xe0\"lfsrsvlsj\"i\x61liif", "nbydghkfvmq\\\xe0\"lfsrsvlsj\"i\x61liif"],
[r"jsas\"u", "jsas\"u"],
[r"odipikxlo", "odipikxlo"],
[r"\"rnubsgwltqkbsu\"pcpcs", "\"rnubsgwltqkbsu\"pcpcs"],
[r"eitk\\f\\mhcqqoym\\ji", "eitk\\f\\mhcqqoym\\ji"],
[r"vnedc", "vnedc"],
[r"\"lhcaurdqzyjyu", "\"lhcaurdqzyjyu"],
[r"haxzsa\"zcn\"y\"foclgtjfcnv\"m\x68krc", "haxzsa\"zcn\"y\"foclgtjfcnv\"m\x68krc"],
[r"\"eoeggg\"tmiydvcay\"vfavc", "\"eoeggg\"tmiydvcay\"vfavc"],
[r"snqvyqoncwxcvwbdktoywch", "snqvyqoncwxcvwbdktoywch"],
[r"rnfgjsyr\xd5wacy", "rnfgjsyr\xd5wacy"],
[r"ik\"hebrpvsts", "ik\"hebrpvsts"],
[r"txw", "txw"],
[r"\x15pxtdkogd\"urbm\"gevhh\"nxr\x3erxtk", "\x15pxtdkogd\"urbm\"gevhh\"nxr\x3erxtk"],
[r"cetqtcy", "cetqtcy"],
[r"inleep\\mgl", "inleep\\mgl"],
[r"uflwbxvww\x2cxzezqnaply\"yh\"qlllzk", "uflwbxvww\x2cxzezqnaply\"yh\"qlllzk"],
[r"eepak\"xqtedzt", "eepak\"xqtedzt"],
[r"na\x61qzfieafvyrsnwkssznohjmc", "na\x61qzfieafvyrsnwkssznohjmc"],
[r"yceaonylz\xc1\\jrlbbkzwsidfi", "yceaonylz\xc1\\jrlbbkzwsidfi"],
[r"ybqafngkcqpbp", "ybqafngkcqpbp"],
[r"\xaft", "\xaft"],
[r"yidjpaobqydso", "yidjpaobqydso"],
[r"ju\\ldxig\\lrdrhjcmm\x77rc", "ju\\ldxig\\lrdrhjcmm\x77rc"],
[r"tylacqeslnwj\x48ds\"tjxa", "tylacqeslnwj\x48ds\"tjxa"],
[r"efbfm", "efbfm"],
[r"\\fxkgoprgdcjgyajykg\\dtbrz", "\\fxkgoprgdcjgyajykg\\dtbrz"],
[r"eujvva", "eujvva"],
[r"h\x7acwfpikme\\vwthyvrqdnx\"", "h\x7acwfpikme\\vwthyvrqdnx\""],
[r"rbpbrxm\\\"\"\"voxx", "rbpbrxm\\\"\"\"voxx"],
[r"ykiw\"tkb\\lforu\"rsf\\tf\"x\"rqti", "ykiw\"tkb\\lforu\"rsf\\tf\"x\"rqti"],
[r"e\\wh\x77aqeugiq\\ihhfqfuaij", "e\\wh\x77aqeugiq\\ihhfqfuaij"],
[r"g\"t\\o", "g\"t\\o"],
[r"nxzo\"hf\\xp", "nxzo\"hf\\xp"],
[r"dxiaqfo\xea", "dxiaqfo\xea"],
[r"kali\\zczhiqkqzybjj\"fgdjnik", "kali\\zczhiqkqzybjj\"fgdjnik"],
[r"zdkgrqmdv", "zdkgrqmdv"],
[r"bimxim\xb6lrwsaj\"ui\"a", "bimxim\xb6lrwsaj\"ui\"a"],
[r"\"rrznitibgx\\olpsjmjqzctxaubdifsq", "\"rrznitibgx\\olpsjmjqzctxaubdifsq"],
[r"zb\"khzixaacmhuzmlymoformipdzml", "zb\"khzixaacmhuzmlymoformipdzml"],
[r"qfwi", "qfwi"],
[r"hjwsxfpphttjy\"\"zixais\xbblgnqfto", "hjwsxfpphttjy\"\"zixais\xbblgnqfto"],
[r"puj\\qmyu\"nqgaqfthbwjokbmrpbhpi", "puj\\qmyu\"nqgaqfthbwjokbmrpbhpi"],
[r"cyxdpkh\\\"", "cyxdpkh\\\""],
[r"q", "q"],
[r"m", "m"],
[r"tbxdzzllarlo", "tbxdzzllarlo"],
[r"gbtys", "gbtys"],
[r"gytilk\\vlqxvcuutjunrqc", "gytilk\\vlqxvcuutjunrqc"],
[r"uugkvcuzan\\eyhb", "uugkvcuzan\\eyhb"],
[r"yaxr\"genlbgw\"\\uc", "yaxr\"genlbgw\"\\uc"],
[r"nrgecjeip\\sjdvgqaqxwsqactopu", "nrgecjeip\\sjdvgqaqxwsqactopu"],
[r"pu\"r\"txpyrkfny\\zmwfneyvwmnkkdipv", "pu\"r\"txpyrkfny\\zmwfneyvwmnkkdipv"],
[r"jm\xa3bhwvq", "jm\xa3bhwvq"],
[r"qxojmnml\"w\x9airr", "qxojmnml\"w\x9airr"],
[r"xbzsuihs\x4dcedy\xaclrhgii\\\"", "xbzsuihs\x4dcedy\xaclrhgii\\\""],
[r"drgjirusrekrwmvxllwdm", "drgjirusrekrwmvxllwdm"],
[r"\x28hfxnfpycmpnkku\"csuf\xaarxlqyg\"x", "\x28hfxnfpycmpnkku\"csuf\xaarxlqyg\"x"],
[r"\"zvz\\rmg\"\\sxxoifffyqfyn\"iq\"ps", "\"zvz\\rmg\"\\sxxoifffyqfyn\"iq\"ps"],
[r"\"z", "\"z"],
[r"zbwkmk\"sgzos\x93gtc\"", "zbwkmk\"sgzos\x93gtc\""],
[r"bvm\x28aa\\\\\"pywuhaniox\\z\\hbp\xd7mold", "bvm\x28aa\\\\\"pywuhaniox\\z\\hbp\xd7mold"],
[r"aszgvsyna", "aszgvsyna"],
[r"qf\"vdwuss", "qf\"vdwuss"],
[r"lnohni\"qwiacjsjegstlbfq\\kyjhyd", "lnohni\"qwiacjsjegstlbfq\\kyjhyd"],
[r"c\\naawulxlqplnacvytspry\xf5ytxxqq", "c\\naawulxlqplnacvytspry\xf5ytxxqq"],
[r"razwqmsqgbaaxcd\\f", "razwqmsqgbaaxcd\\f"],
[r"radggyrjrg\"zx", "radggyrjrg\"zx"],
[r"\"pu\x11t\\ajcjuieinlkvya", "\"pu\x11t\\ajcjuieinlkvya"],
[r"veggiskh", "veggiskh"],
[r"eglfhjxiet\"kouqfskwsy\"hpthsldel", "eglfhjxiet\"kouqfskwsy\"hpthsldel"],
[r"mv\xc1b\"f\\shrssnjwcpmurepdxdlcj", "mv\xc1b\"f\\shrssnjwcpmurepdxdlcj"],
[r"dlayjd\"suvzotgdtc", "dlayjd\"suvzotgdtc"],
[r"\xa9pvxeopn", "\xa9pvxeopn"],
[r"lpplsaxy\"oiwaq", "lpplsaxy\"oiwaq"],
[r"hqwh\\lusv", "hqwh\\lusv"],
[r"hykykwlx\"\xa5atkgh\\d\x63dff", "hykykwlx\"\xa5atkgh\\d\x63dff"],
[r"vfktanpjy\"xxetc", "vfktanpjy\"xxetc"],
[r"dnhwkgjnsmsswfuelvihvjl\"jtf", "dnhwkgjnsmsswfuelvihvjl\"jtf"],
[r"x\"dwvzra\"nbbsewftehczgbvfzd\"rau", "x\"dwvzra\"nbbsewftehczgbvfzd\"rau"],
[r"csfi\"mzejnjqkqupwadrgti\"von", "csfi\"mzejnjqkqupwadrgti\"von"],
[r"xckf\xf7xsm\\pgvlpetjndpyblais\\z", "xckf\xf7xsm\\pgvlpetjndpyblais\\z"],
[r"yecy\x6fuj\x58bwpgeuiw\"mdu", "yecy\x6fuj\x58bwpgeuiw\"mdu"],
[r"fgb", "fgb"],
[r"c\\lx\x3efthet\xfdelgvwvpem", "c\\lx\x3efthet\xfdelgvwvpem"],
[r"kgyrmarvfwjinlowt", "kgyrmarvfwjinlowt"],
[r"yzte", "yzte"],
[r"vc\"z", "vc\"z"],
[r"sxevqfzmmdwsuu\"", "sxevqfzmmdwsuu\""],
[r"fxbaercmcy\xb6md", "fxbaercmcy\xb6md"],
[r"f", "f"],
[r"m\x44gqbcppho\\b", "m\x44gqbcppho\\b"],
[r"gtafr\x57m\x11jy\"\"erwmmpiwjkbckuw", "gtafr\x57m\x11jy\"\"erwmmpiwjkbckuw"],
[r"ufdjt\"kssprzxqixzxmq\x58q", "ufdjt\"kssprzxqixzxmq\x58q"],
[r"yzbyo\"lfdbyaxexyfbnyv\\\xe8xmre", "yzbyo\"lfdbyaxexyfbnyv\\\xe8xmre"],
[r"u\x43ntr\\\\byyfjr\"iveujvnwsqbnpuvrta", "u\x43ntr\\\\byyfjr\"iveujvnwsqbnpuvrta"],
[r"us\xf6bai", "us\xf6bai"],
[r"c\\edh", "c\\edh"],
[r"tzckolphexfq\\\x23\xfbdqv\\\"m", "tzckolphexfq\\\x23\xfbdqv\\\"m"],
[r"yjafhbvhhj\x1b\"bplb", "yjafhbvhhj\x1b\"bplb"],
[r"\"o", "\"o"],
[r"rubahvmp\"", "rubahvmp\""],
[r"qmkukrnrmqumh", "qmkukrnrmqumh"],
[r"wdpxyvyidhwjf\\nabbijwhr\xc5bksvy\"p", "wdpxyvyidhwjf\\nabbijwhr\xc5bksvy\"p"],
[r"u\"prlpg\"", "u\"prlpg\""],
[r"nsvcquyxbwilsxxemf\xd9leq", "nsvcquyxbwilsxxemf\xd9leq"],
[r"y\xcetxuafl", "y\xcetxuafl"],
[r"it", "it"],
[r"kwdlysf\\xjpelae", "kwdlysf\\xjpelae"],
[r"viwh\x58wpjjlnvryuti\x2chngrx\\nhtkui", "viwh\x58wpjjlnvryuti\x2chngrx\\nhtkui"],
[r"vhn\x9ehre\xc3ncsqbozms\"nl", "vhn\x9ehre\xc3ncsqbozms\"nl"],
[r"ytc\xa3mgeeogjcqavmmmd", "ytc\xa3mgeeogjcqavmmmd"],
[r"xzlexlitseozoxtpzzutfq", "xzlexlitseozoxtpzzutfq"],
[r"cish\x07lmovj", "cish\x07lmovj"],
[r"ekbflwqzaiivdr\"pq\\azrfbntqwkn", "ekbflwqzaiivdr\"pq\\azrfbntqwkn"],
[r"uc\"xdbegmlmhksofzohavtrnxf", "uc\"xdbegmlmhksofzohavtrnxf"],
[r"xfdnrdqdrcjzbe", "xfdnrdqdrcjzbe"],
[r"ndg\"ckgrpisib\"rg\"p\\lmpfzlssnvk", "ndg\"ckgrpisib\"rg\"p\\lmpfzlssnvk"],
[r"witfjwpbyyzlop", "witfjwpbyyzlop"],
[r"zonlww\"emrbcsgdtrg\"rjzy\x64zqntlw", "zonlww\"emrbcsgdtrg\"rjzy\x64zqntlw"],
[r"dvgb\"zn\\vrbzema\"ckmd", "dvgb\"zn\\vrbzema\"ckmd"],
[r"\\vdlmxhlvldk\"pmzazeip", "\\vdlmxhlvldk\"pmzazeip"],
[r"\"\"r", "\"\"r"],
[r"rsntinv", "rsntinv"],
[r"iy", "iy"],
[r"lr\x20efh", "lr\x20efh"],
[r"csgexlb\"zqdavlxxhtdbh\"\"\x0fkpvhiphm", "csgexlb\"zqdavlxxhtdbh\"\"\x0fkpvhiphm"],
[r"ouwhp\"ogbft", "ouwhp\"ogbft"],
[r"cm\\ckltng\"dw\x8brf\xf0eppgckd", "cm\\ckltng\"dw\x8brf\xf0eppgckd"],
[r"zmnlsgalhpkejsizfsbtnfliu\"nhc", "zmnlsgalhpkejsizfsbtnfliu\"nhc"],
[r"pnrkaayqvwpdjbhcrbb\"yfeq\"aq", "pnrkaayqvwpdjbhcrbb\"yfeq\"aq"],
[r"ozh\\hoxow\x2csrtr\\r\"", "ozh\\hoxow\x2csrtr\\r\""],
[r"bqxabj\"u\\s", "bqxabj\"u\\s"],
[r"cpsjti\"gy", "cpsjti\"gy"],
[r"aa\"p\\nki\\ajijkqev", "aa\"p\\nki\\ajijkqev"],
[r"q\"\"lfdentjgd\\", "q\"\"lfdentjgd\\"],
[r"bmokvpoebutfki", "bmokvpoebutfki"],
[r"pielvcbne\xf6efvzxn", "pielvcbne\xf6efvzxn"],
[r"kx", "kx"],
[r"zlgmqagcrbhrwtwtmmg", "zlgmqagcrbhrwtwtmmg"],
[r"aiyhmntcqjbpv\xb5hhswxbryoedvos", "aiyhmntcqjbpv\xb5hhswxbryoedvos"],
[r"tdpaxrb", "tdpaxrb"],
[r"fu\"\x7dttkyvhrlwko", "fu\"\x7dttkyvhrlwko"],
[r"oirc\\\"cqlnqffjqt\\k", "oirc\\\"cqlnqffjqt\\k"],
[r"edxlia\\tcyby", "edxlia\\tcyby"],
[r"jpeybgwfayerfrfbvfog\"ol", "jpeybgwfayerfrfbvfog\"ol"],
[r"ysr", "ysr"],
[r"bzwzilgwfugjk", "bzwzilgwfugjk"],
[r"tlcc\x75nukvwjgftetjcs\xaecwc", "tlcc\x75nukvwjgftetjcs\xaecwc"],
[r"dsqssa\"vzrf\"sewbp\\ahhlmhbeihlh", "dsqssa\"vzrf\"sewbp\\ahhlmhbeihlh"],
[r"qtgmjck\"n\"guki\"gmdivwqxismqj", "qtgmjck\"n\"guki\"gmdivwqxismqj"],
[r"\"f", "\"f"],
[r"wuorvlovucngbzdszqpikyk", "wuorvlovucngbzdszqpikyk"],
[r"dfrdsacoukmgvhbq\"\"iwto", "dfrdsacoukmgvhbq\"\"iwto"],
[r"\"ey\"ch\\wcgioe\\\"ouvligmsw", "\"ey\"ch\\wcgioe\\\"ouvligmsw"],
[r"ciqlszzgs", "ciqlszzgs"],
[r"\\tzyrkaoi\"sopjaq", "\\tzyrkaoi\"sopjaq"],
[r"lmtnv", "lmtnv"],
[r"ar\"fqoroigiertjjlm\"ymgi\\kkjewsxd", "ar\"fqoroigiertjjlm\"ymgi\\kkjewsxd"],
[r"wehcimlvudpxtamdn\"rwy", "wehcimlvudpxtamdn\"rwy"],
[r"hr\"zvrwthr\"vruzqfrldn\"b", "hr\"zvrwthr\"vruzqfrldn\"b"],
[r"sggekodkiwvym\"mhsco", "sggekodkiwvym\"mhsco"],
[r"ltlkfbrrdvk\\", "ltlkfbrrdvk\\"],
[r"uut\"sfjnz\"\\ef", "uut\"sfjnz\"\\ef"],
[r"hxilg\\", "hxilg\\"],
[r"zsredsiwlzrpedibn", "zsredsiwlzrpedibn"],
[r"vtfi", "vtfi"],
[r"\\h", "\\h"],
[r"qekfrc\xf6wduodbwrguqcng\\n", "qekfrc\xf6wduodbwrguqcng\\n"],
[r"\"lljlfdrxftwidn\\pkv\xd9ij", "\"lljlfdrxftwidn\\pkv\xd9ij"],
[r"mrvgqynpehkliuijlpp", "mrvgqynpehkliuijlpp"],
[r"gikjph", "gikjph"],
[r"yoxcdrdt\"wbaurnyhoyxoihu", "yoxcdrdt\"wbaurnyhoyxoihu"],
[r"onmomwuxuammbzxe", "onmomwuxuammbzxe"],
[r"rnrr\\twviz\x61gqaljr\x0dmtw", "rnrr\\twviz\x61gqaljr\x0dmtw"],
[r"r\"vupaoi", "r\"vupaoi"],
[r"l", "l"],
[r"sei", "sei"],
[r"jwxtdtbkd\\kxd", "jwxtdtbkd\\kxd"],
[r"\x22v\\", "\x22v\\"],
[r"ahd", "ahd"],
[r"j\"bjqxs", "j\"bjqxs"],
[r"\\i\x24gglxub\\nzsajokt", "\\i\x24gglxub\\nzsajokt"],
[r"lviwpu\"uxdlh\\zuy\"xqy\"ytdzlx\"r", "lviwpu\"uxdlh\\zuy\"xqy\"ytdzlx\"r"],
[r"kptfmys", "kptfmys"],
[r"fwxzikfhczkjwyjszqdbkepaeellc", "fwxzikfhczkjwyjszqdbkepaeellc"],
[r"nlqpsvbrbd\\ns", "nlqpsvbrbd\\ns"],
[r"qryuwkjiodw\"\"vaqyq\"dmyifm", "qryuwkjiodw\"\"vaqyq\"dmyifm"],
[r"tw\x15kdmaudjl\\zorhp\"alwh", "tw\x15kdmaudjl\\zorhp\"alwh"],
[r"aatrvczesykekkjfyb\"kb", "aatrvczesykekkjfyb\"kb"],
[r"usqcutbqbxxhucwxo\xc1ltb\"j\"bghjcvws", "usqcutbqbxxhucwxo\xc1ltb\"j\"bghjcvws"],
[r"ilhsrnzxkz", "ilhsrnzxkz"],
[r"bianqfdfdhvw", "bianqfdfdhvw"],
[r"hqibqs\x7ax\"qoxqoaqtcsz", "hqibqs\x7ax\"qoxqoaqtcsz"],
[r"htxtoojbbauztwxuiq\\ngyfy\\obzc", "htxtoojbbauztwxuiq\\ngyfy\\obzc"],
[r"rxn\\moxlj", "rxn\\moxlj"],
[r"mtus\x84erh\"dbe", "mtus\x84erh\"dbe"],
[r"asx\x50huvsitcxadt", "asx\x50huvsitcxadt"],
[r"\"bugggtnrc\"\"kl\"hmpu\x83hqrvhpo", "\"bugggtnrc\"\"kl\"hmpu\x83hqrvhpo"],
[r"ewisbp\"\"vuzf\\w\x5fvalszdhl", "ewisbp\"\"vuzf\\w\x5fvalszdhl"],
[r"scusplpwxfnxu\x57\"zynpn\x99xerc\\ri", "scusplpwxfnxu\x57\"zynpn\x99xerc\\ri"],
[r"m\\kinmkke\x0cl", "m\\kinmkke\x0cl"],
[r"xhuzit\x7fd", "xhuzit\x7fd"],
[r"kfbo\x04\x50ruqirn", "kfbo\x04\x50ruqirn"],
[r"t\"\"xpbdscmdoug", "t\"\"xpbdscmdoug"],
[r"punvpsgnbgyxe\"sptmpz", "punvpsgnbgyxe\"sptmpz"],
[r"bxukkazijr", "bxukkazijr"],
[r"nxyrcdaoo\"rjkk\"wntehcvcip\"vrd", "nxyrcdaoo\"rjkk\"wntehcvcip\"vrd"],
[r"rdpvqskmihqaw", "rdpvqskmihqaw"],
[r"p\\gwdhtqnpgthod", "p\\gwdhtqnpgthod"],
[r"nwnuf\"\"yebycearom\"nqym\"\xd4sii\xccle", "nwnuf\"\"yebycearom\"nqym\"\xd4sii\xccle"],
[r"alda\"ptspo\"wkkv\"zoi\"hkb\"vnntyd", "alda\"ptspo\"wkkv\"zoi\"hkb\"vnntyd"],
[r"ixpgpfzbqv", "ixpgpfzbqv"],
[r"znui\"\\fzn\x03qozabh\"rva\"pv\x67", "znui\"\\fzn\x03qozabh\"rva\"pv\x67"],
[r"e\"zswmwuk", "e\"zswmwuk"],
[r"hcccygwfa", "hcccygwfa"],
[r"ngmace\\rtyllolr\"\x68bw", "ngmace\\rtyllolr\"\x68bw"],
[r"\\c\"jyufbry\"ryo\"xpo\x26ecninfeckh\\s", "\\c\"jyufbry\"ryo\"xpo\x26ecninfeckh\\s"],
[r"hdnpngtuc\"dzbvvosn\x31fwtpzbrt", "hdnpngtuc\"dzbvvosn\x31fwtpzbrt"],
[r"hesbpd\xd4", "hesbpd\xd4"],
[r"dsdbstuzrdfmrnyntufs\"dmv", "dsdbstuzrdfmrnyntufs\"dmv"],
[r"d\xeeibcwhcvkt", "d\xeeibcwhcvkt"],
[r"fvzwrsfjdqdmy\"\"v", "fvzwrsfjdqdmy\"\"v"],
[r"ns\"dqafz\\lkyoflnazv\"mn\x37\"o\"yj\"e", "ns\"dqafz\\lkyoflnazv\"mn\x37\"o\"yj\"e"],
[r"dypilgbwzccayxa\"bnmuernx", "dypilgbwzccayxa\"bnmuernx"],
[r"q\xa9ztqrhreb\"\"kxfeyodqb", "q\xa9ztqrhreb\"\"kxfeyodqb"],
[r"iz\xa5qjxqulaawuwz\"rqmpcj\\yel", "iz\xa5qjxqulaawuwz\"rqmpcj\\yel"],
[r"z\"\\pq\"\"y\x67zpjtn", "z\"\\pq\"\"y\x67zpjtn"],
[r"ifxqvivp\"kiiftdoe", "ifxqvivp\"kiiftdoe"],
[r"jxzebj\"\x35\"qr\"ecglcutuoyywqumcs\"kk", "jxzebj\"\x35\"qr\"ecglcutuoyywqumcs\"kk"],
[r"q", "q"],
[r"yob\x85qmpuwexptczbkrl", "yob\x85qmpuwexptczbkrl"],
[r"cjiavv\"uudpozvibyycnmxhxpxmpjoz", "cjiavv\"uudpozvibyycnmxhxpxmpjoz"],
[r"xro\\uiqyrcid", "xro\\uiqyrcid"],
[r"nod\\k", "nod\\k"],
[r"d\"neiec", "d\"neiec"],
[r"tqyrqvwyvmz\\pzgzzcqsqsrgbqbtapoz", "tqyrqvwyvmz\\pzgzzcqsqsrgbqbtapoz"],
[r"r\"xvocpeuxfxslgueb\x05kzyyie\"aoec", "r\"xvocpeuxfxslgueb\x05kzyyie\"aoec"],
[r"\"du\\uirlhcbgv\\cjqhfreqnvn", "\"du\\uirlhcbgv\\cjqhfreqnvn"],
[r"zp\x04\x15\"pbjwhrjtmiba", "zp\x04\x15\"pbjwhrjtmiba"],
[r"\\cv\"", "\\cv\""],
[r"k\"rwnb\\hiu\"rqd\"rc\\nyakrhly", "k\"rwnb\\hiu\"rqd\"rc\\nyakrhly"],
[r"klrmafjzandiddodgz", "klrmafjzandiddodgz"],
[r"xipzhqzhvlpykzcuppx", "xipzhqzhvlpykzcuppx"],
[r"zdvrvn\xd0mtfvpylbn\\\\sxcznrzugwznl", "zdvrvn\xd0mtfvpylbn\\\\sxcznrzugwznl"],
[r"ody\\pvm\"kpjiudzhxazirgxzvumeat\"o", "ody\\pvm\"kpjiudzhxazirgxzvumeat\"o"],
[r"kllvhdp\"prjikzrrc\"adgpegc\\\"gk", "kllvhdp\"prjikzrrc\"adgpegc\\\"gk"],
[r"sqtpug\xbcaauxaamw", "sqtpug\xbcaauxaamw"],
[r"wegxxrrxdvpivrqievfeokmnojsk", "wegxxrrxdvpivrqievfeokmnojsk"],
[r"\\bo", "\\bo"],
[r"gijhz", "gijhz"],
[r"ylowluvabwrigssdgtxdwsiorxev\xdd", "ylowluvabwrigssdgtxdwsiorxev\xdd"],
[r"\"", "\""],
[r"ghnsrnsqtxpygikahkrl", "ghnsrnsqtxpygikahkrl"],
[r"\"rcfqkbjf\"sgxg\"vnd\\rotn", "\"rcfqkbjf\"sgxg\"vnd\\rotn"],
[r"ap\"smgsuexjrbuqs\"mpbstogj\"x", "ap\"smgsuexjrbuqs\"mpbstogj\"x"],
[r"koaunz\\sgt\"opv", "koaunz\\sgt\"opv"],
[r"yialiuzwix", "yialiuzwix"],
[r"yp\"ndxgwzml\"bt", "yp\"ndxgwzml\"bt"],
[r"lpcjxmggfsy\\szbxccarjkqzasqkb\xcfd\x0c", "lpcjxmggfsy\\szbxccarjkqzasqkb\xcfd\x0c"],
[r"x", "x"],
[r"mgakc", "mgakc"],
[r"vjieunoh\x73fjwx", "vjieunoh\x73fjwx"],
[r"erbvv\"qulsd", "erbvv\"qulsd"],
[r"mimycrbfhqkarmz", "mimycrbfhqkarmz"],
[r"tihfbgcszuej\"c\xfbvoqskkhbgpaddioo", "tihfbgcszuej\"c\xfbvoqskkhbgpaddioo"],
[r"mziavkwrmekriqghw", "mziavkwrmekriqghw"],
[r"izk\\tnjd\\ed\\emokvjoc", "izk\\tnjd\\ed\\emokvjoc"],
[r"c\"nhbqzndro\\g", "c\"nhbqzndro\\g"],
[r"usfngdo", "usfngdo"],
[r"aypljdftvptt", "aypljdftvptt"],
[r"ym\"afvq\xbcc", "ym\"afvq\xbcc"],
[r"zabi\"wjpvugwhl", "zabi\"wjpvugwhl"],
[r"ebvptcjqjhc\"n\"p\"dxrphegr\\", "ebvptcjqjhc\"n\"p\"dxrphegr\\"],
[r"mzlqqxokhye\xd9\\rffhnzs", "mzlqqxokhye\xd9\\rffhnzs"],
[r"hnipqknwpsjakanuewe", "hnipqknwpsjakanuewe"],
[r"rqgbfcjdrmiz\"h", "rqgbfcjdrmiz\"h"],
[r"kzzp\\z\\txmkwaouxictybwx", "kzzp\\z\\txmkwaouxictybwx"],
[r"yzmspjkqrteiydswlvb", "yzmspjkqrteiydswlvb"],
[r"gjpxklgpzv\"txri\\hotpuiukzzzd", "gjpxklgpzv\"txri\\hotpuiukzzzd"],
[r"p\"rxergtbsxmjmkeeqwvoagnki\"", "p\"rxergtbsxmjmkeeqwvoagnki\""],
[r"santipvuiq", "santipvuiq"],
[r"\"ihjqlhtwbuy\"hdkiv\"mtiqacnf\\", "\"ihjqlhtwbuy\"hdkiv\"mtiqacnf\\"],
[r"oliaggtqyyx", "oliaggtqyyx"],
[r"fwwnpmbb", "fwwnpmbb"],
[r"yrtdrieazfxyyneo", "yrtdrieazfxyyneo"],
[r"nywbv\\", "nywbv\\"],
[r"twc\\ehfqxhgomgrgwpxyzmnkioj", "twc\\ehfqxhgomgrgwpxyzmnkioj"],
[r"qludrkkvljljd\\xvdeum\x4e", "qludrkkvljljd\\xvdeum\x4e"],
]

inputString2 = [
[r"", ""],
[r"asd", "asd"],
[r"aaa\"aaa", "aaa\"aaa"],
[r"\x27", "\x27"],
]

main(inputString)
main2(inputString2)
