#!/usr/bin/python

import re
import sys

s = ''
def main(string):
   logic = {}
   for i in string:
      logic[i.split(' -> ')[1]] = i.split(' -> ')[0]
   for key in [
         "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
         "aa", "ab", "ac", "ad", "ae", "af", "ag", "ah", "ai", "aj", "ak", "al", "am", "an", "ao", "ap", "aq", "ar", "as", "at", "au", "av", "aw", "ax", "ay", "az",
         "ba", "bb", "bc", "bd", "be", "bf", "bg", "bh", "bi", "bj", "bk", "bl", "bm", "bn", "bo", "bp", "bq", "br", "bs", "bt", "bu", "bv", "bw", "bx", "by", "bz",
         "ca", "cb", "cc", "cd", "ce", "cf", "cg", "ch", "ci", "cj", "ck", "cl", "cm", "cn", "co", "cp", "cq", "cr", "cs", "ct", "cu", "cv", "cw", "cx", "cy", "cz",
         "da", "db", "dc", "dd", "de", "df", "dg", "dh", "di", "dj", "dk", "dl", "dm", "dn", "do", "dp", "dq", "dr", "ds", "dt", "du", "dv", "dw", "dx", "dy", "dz",
         "ea", "eb", "ec", "ed", "ee", "ef", "eg", "eh", "ei", "ej", "ek", "el", "em", "en", "eo", "ep", "eq", "er", "es", "et", "eu", "ev", "ew", "ex", "ey", "ez",
         "fa", "fb", "fc", "fd", "fe", "ff", "fg", "fh", "fi", "fj", "fk", "fl", "fm", "fn", "fo", "fp", "fq", "fr", "fs", "ft", "fu", "fv", "fw", "fx", "fy", "fz",
         "ga", "gb", "gc", "gd", "ge", "gf", "gg", "gh", "gi", "gj", "gk", "gl", "gm", "gn", "go", "gp", "gq", "gr", "gs", "gt", "gu", "gv", "gw", "gx", "gy", "gz",
         "ha", "hb", "hc", "hd", "he", "hf", "hg", "hh", "hi", "hj", "hk", "hl", "hm", "hn", "ho", "hp", "hq", "hr", "hs", "ht", "hu", "hv", "hw", "hx", "hy", "hz",
         "ia", "ib", "ic", "id", "ie", "if", "ig", "ih", "ii", "ij", "ik", "il", "im", "in", "io", "ip", "iq", "ir", "is", "it", "iu", "iv", "iw", "ix", "iy", "iz",
         "ja", "jb", "jc", "jd", "je", "jf", "jg", "jh", "ji", "jj", "jk", "jl", "jm", "jn", "jo", "jp", "jq", "jr", "js", "jt", "ju", "jv", "jw", "jx", "jy", "jz",
         "ka", "kb", "kc", "kd", "ke", "kf", "kg", "kh", "ki", "kj", "kk", "kl", "km", "kn", "ko", "kp", "kq", "kr", "ks", "kt", "ku", "kv", "kw", "kx", "ky", "kz",
      ]:
      s = evaluate(logic[key], logic, "")
      tmp = eval(s)
      #print "Key: '{}'\n\tValue1: '{}'\n\tValue2: '{}'\n\tEvaluated: '{}'".format(key, logic[key], s, tmp)
      if int(tmp) >= 0:
         logic[key] = str(tmp)
   #for key in logic.keys():
   #   print '{}\t{}'.format(key, logic[key])
   s = evaluate('a', logic, "")
   print "Result: {}".format(eval(s))

def evaluate(string, logic, s):
   if not re.match('0|1|2|3|4|5|6|7|8|9', string):
      s = s + '( '
   for i in string.split(' '):
      #print "CURRENT STRING " + i
      if re.match('0|1|2|3|4|5|6|7|8|9|OR|AND|NOT|LSHIFT|RSHIFT', i):
         if re.match('0|1|2|3|4|5|6|7|8|9', i):
            s = s + ' {} '.format(int(i))
         else:
            if i == "AND":
               s = s + ' & '
            elif i == "OR":
               s = s + ' | '
            elif i == "NOT":
               s = s + ' ~ '
            elif re.match('LSHIFT|RSHIFT', i):
               shiftBy = i.split('_')
               if re.match('LSHIFT', i):
                  shift = '<<'
               else:
                  shift = '>>'
               s = s + ' {} {} '.format(shift, shiftBy[1])
            else:
               s = s + ' {} '.format(i)
      else:
         s = evaluate(logic[i], logic, s)
   if not re.match('0|1|2|3|4|5|6|7|8|9', string):
      s = s + ') '
   return s

inputString = [
"NOT dq -> dr",
"kg OR kf -> kh",
"ep OR eo -> eq",
"44430 -> b",
"NOT gs -> gt",
"dd OR do -> dp",
"eg AND ei -> ej",
"y AND ae -> ag",
"jx AND jz -> ka",
"lf RSHIFT_2 -> lg",
"z AND aa -> ac",
"dy AND ej -> el",
"bj OR bi -> bk",
"kk RSHIFT_3 -> km",
"NOT cn -> co",
"gn AND gp -> gq",
"cq AND cs -> ct",
"eo LSHIFT_15 -> es",
"lg OR lm -> ln",
"dy OR ej -> ek",
"NOT di -> dj",
"1 AND fi -> fj",
"kf LSHIFT_15 -> kj",
"NOT jy -> jz",
"NOT ft -> fu",
"fs AND fu -> fv",
"NOT hr -> hs",
"ck OR cl -> cm",
"jp RSHIFT_5 -> js",
"iv OR jb -> jc",
"is OR it -> iu",
"ld OR le -> lf",
"NOT fc -> fd",
"NOT dm -> dn",
"bn OR by -> bz",
"aj AND al -> am",
"cd LSHIFT_15 -> ch",
"jp AND ka -> kc",
"ci OR ct -> cu",
"gv AND gx -> gy",
"de AND dk -> dm",
"x RSHIFT_5 -> aa",
"et RSHIFT_2 -> eu",
"x RSHIFT_1 -> aq",
"ia OR ig -> ih",
"bk LSHIFT_1 -> ce",
"y OR ae -> af",
"NOT ca -> cb",
"e AND f -> h",
"ia AND ig -> ii",
"ck AND cl -> cn",
"NOT jh -> ji",
"z OR aa -> ab",
"1 AND en -> eo",
"ib AND ic -> ie",
"NOT eh -> ei",
"iy AND ja -> jb",
"NOT bb -> bc",
"ha OR gz -> hb",
"1 AND cx -> cy",
"NOT ax -> ay",
"ev OR ew -> ex",
"bn RSHIFT_2 -> bo",
"er OR es -> et",
"eu OR fa -> fb",
"jp OR ka -> kb",
"ea AND eb -> ed",
"k AND m -> n",
"et RSHIFT_3 -> ev",
"et RSHIFT_5 -> ew",
"hz RSHIFT_1 -> is",
"ki OR kj -> kk",
"NOT h -> i",
"lv LSHIFT_15 -> lz",
"as RSHIFT_1 -> bl",
"hu LSHIFT_15 -> hy",
"iw AND ix -> iz",
"lf RSHIFT_1 -> ly",
"fp OR fv -> fw",
"1 AND am -> an",
"ap LSHIFT_1 -> bj",
"u LSHIFT_1 -> ao",
"b RSHIFT_5 -> f",
"jq AND jw -> jy",
"iu RSHIFT_3 -> iw",
"ih AND ij -> ik",
"NOT iz -> ja",
"de OR dk -> dl",
"iu OR jf -> jg",
"as AND bd -> bf",
"b RSHIFT_3 -> e",
"jq OR jw -> jx",
"iv AND jb -> jd",
"cg OR ch -> ci",
"iu AND jf -> jh",
"lx -> a",
"1 AND cc -> cd",
"ly OR lz -> ma",
"NOT el -> em",
"1 AND bh -> bi",
"fb AND fd -> fe",
"lf OR lq -> lr",
"bn RSHIFT_3 -> bp",
"bn AND by -> ca",
"af AND ah -> ai",
"cf LSHIFT_1 -> cz",
"dw OR dx -> dy",
"gj AND gu -> gw",
"jg AND ji -> jj",
"jr OR js -> jt",
"bl OR bm -> bn",
"gj RSHIFT_2 -> gk",
"cj OR cp -> cq",
"gj OR gu -> gv",
"b OR n -> o",
"o AND q -> r",
"bi LSHIFT_15 -> bm",
"dy RSHIFT_1 -> er",
"cu AND cw -> cx",
"iw OR ix -> iy",
"hc OR hd -> he",
"0 -> c",
"db OR dc -> dd",
"kk RSHIFT_2 -> kl",
"eq LSHIFT_1 -> fk",
"dz OR ef -> eg",
"NOT ed -> ee",
"lw OR lv -> lx",
"fw AND fy -> fz",
"dz AND ef -> eh",
"jp RSHIFT_3 -> jr",
"lg AND lm -> lo",
"ci RSHIFT_2 -> cj",
"be AND bg -> bh",
"lc LSHIFT_1 -> lw",
"hm AND ho -> hp",
"jr AND js -> ju",
"1 AND io -> ip",
"cm AND co -> cp",
"ib OR ic -> id",
"NOT bf -> bg",
"fo RSHIFT_5 -> fr",
"ip LSHIFT_15 -> it",
"jt AND jv -> jw",
"jc AND je -> jf",
"du OR dt -> dv",
"NOT fx -> fy",
"aw AND ay -> az",
"ge LSHIFT_15 -> gi",
"NOT ak -> al",
"fm OR fn -> fo",
"ff AND fh -> fi",
"ci RSHIFT_5 -> cl",
"cz OR cy -> da",
"NOT ey -> ez",
"NOT ju -> jv",
"NOT ls -> lt",
"kk AND kv -> kx",
"NOT ii -> ij",
"kl AND kr -> kt",
"jk LSHIFT_15 -> jo",
"e OR f -> g",
"NOT bs -> bt",
"hi AND hk -> hl",
"hz OR ik -> il",
"ek AND em -> en",
"ao OR an -> ap",
"dv LSHIFT_1 -> ep",
"an LSHIFT_15 -> ar",
"fo RSHIFT_1 -> gh",
"NOT im -> in",
"kk RSHIFT_1 -> ld",
"hw LSHIFT_1 -> iq",
"ec AND ee -> ef",
"hb LSHIFT_1 -> hv",
"kb AND kd -> ke",
"x AND ai -> ak",
"dd AND do -> dq",
"aq OR ar -> as",
"iq OR ip -> ir",
"dl AND dn -> do",
"iu RSHIFT_5 -> ix",
"as OR bd -> be",
"NOT go -> gp",
"fk OR fj -> fl",
"jm LSHIFT_1 -> kg",
"NOT cv -> cw",
"dp AND dr -> ds",
"dt LSHIFT_15 -> dx",
"et RSHIFT_1 -> fm",
"dy RSHIFT_3 -> ea",
"fp AND fv -> fx",
"NOT p -> q",
"dd RSHIFT_2 -> de",
"eu AND fa -> fc",
"ba AND bc -> bd",
"dh AND dj -> dk",
"lr AND lt -> lu",
"he RSHIFT_1 -> hx",
"ex AND ez -> fa",
"df OR dg -> dh",
"fj LSHIFT_15 -> fn",
"NOT kx -> ky",
"gk OR gq -> gr",
"dy RSHIFT_2 -> dz",
"gh OR gi -> gj",
"lj AND ll -> lm",
"x OR ai -> aj",
"bz AND cb -> cc",
"1 AND lu -> lv",
"as RSHIFT_3 -> au",
"ce OR cd -> cf",
"il AND in -> io",
"dd RSHIFT_1 -> dw",
"NOT lo -> lp",
"c LSHIFT_1 -> t",
"dd RSHIFT_3 -> df",
"dd RSHIFT_5 -> dg",
"lh AND li -> lk",
"lf RSHIFT_5 -> li",
"dy RSHIFT_5 -> eb",
"NOT kt -> ku",
"at OR az -> ba",
"x RSHIFT_3 -> z",
"NOT lk -> ll",
"lb OR la -> lc",
"1 AND r -> s",
"lh OR li -> lj",
"ln AND lp -> lq",
"kk RSHIFT_5 -> kn",
"ea OR eb -> ec",
"ci AND ct -> cv",
"b RSHIFT_2 -> d",
"jp RSHIFT_1 -> ki",
"NOT cr -> cs",
"NOT jd -> je",
"jp RSHIFT_2 -> jq",
"jn OR jo -> jp",
"lf RSHIFT_3 -> lh",
"1 AND ds -> dt",
"lf AND lq -> ls",
"la LSHIFT_15 -> le",
"NOT fg -> fh",
"at AND az -> bb",
"au AND av -> ax",
"kw AND ky -> kz",
"v OR w -> x",
"kk OR kv -> kw",
"ks AND ku -> kv",
"kh LSHIFT_1 -> lb",
"1 AND kz -> la",
"NOT kc -> kd",
"x RSHIFT_2 -> y",
"et OR fe -> ff",
"et AND fe -> fg",
"NOT ac -> ad",
"jl OR jk -> jm",
"1 AND jj -> jk",
"bn RSHIFT_1 -> cg",
"NOT kp -> kq",
"ci RSHIFT_3 -> ck",
"ev AND ew -> ey",
"1 AND ke -> kf",
"cj AND cp -> cr",
"ir LSHIFT_1 -> jl",
"NOT gw -> gx",
"as RSHIFT_2 -> at",
"iu RSHIFT_1 -> jn",
"cy LSHIFT_15 -> dc",
"hg OR hh -> hi",
"ci RSHIFT_1 -> db",
"au OR av -> aw",
"km AND kn -> kp",
"gj RSHIFT_1 -> hc",
"iu RSHIFT_2 -> iv",
"ab AND ad -> ae",
"da LSHIFT_1 -> du",
"NOT bw -> bx",
"km OR kn -> ko",
"ko AND kq -> kr",
"bv AND bx -> by",
"kl OR kr -> ks",
"1 AND ht -> hu",
"df AND dg -> di",
"NOT ag -> ah",
"d OR j -> k",
"d AND j -> l",
"b AND n -> p",
"gf OR ge -> gg",
"gg LSHIFT_1 -> ha",
"bn RSHIFT_5 -> bq",
"bo OR bu -> bv",
"1 AND gy -> gz",
"s LSHIFT_15 -> w",
"NOT ie -> if",
"as RSHIFT_5 -> av",
"bo AND bu -> bw",
"hz AND ik -> im",
"bp AND bq -> bs",
"b RSHIFT_1 -> v",
"NOT l -> m",
"bp OR bq -> br",
"g AND i -> j",
"br AND bt -> bu",
"t OR s -> u",
"hz RSHIFT_5 -> ic",
"gk AND gq -> gs",
"fl LSHIFT_1 -> gf",
"he RSHIFT_3 -> hg",
"gz LSHIFT_15 -> hd",
"hf OR hl -> hm",
"1 AND gd -> ge",
"fo OR fz -> ga",
"id AND if -> ig",
"fo AND fz -> gb",
"gr AND gt -> gu",
"he OR hp -> hq",
"fq AND fr -> ft",
"ga AND gc -> gd",
"fo RSHIFT_2 -> fp",
"gl OR gm -> gn",
"hg AND hh -> hj",
"NOT hn -> ho",
"gl AND gm -> go",
"he RSHIFT_5 -> hh",
"NOT gb -> gc",
"hq AND hs -> ht",
"hz RSHIFT_3 -> ib",
"hz RSHIFT_2 -> ia",
"fq OR fr -> fs",
"hx OR hy -> hz",
"he AND hp -> hr",
"gj RSHIFT_5 -> gm",
"hf AND hl -> hn",
"hv OR hu -> hw",
"NOT hj -> hk",
"gj RSHIFT_3 -> gl",
"fo RSHIFT_3 -> fq",
"he RSHIFT_2 -> hf"
]

inputString2 = [
"NOT dq -> dr",
"kg OR kf -> kh",
"ep OR eo -> eq",
"3176 -> b",
"NOT gs -> gt",
"dd OR do -> dp",
"eg AND ei -> ej",
"y AND ae -> ag",
"jx AND jz -> ka",
"lf RSHIFT_2 -> lg",
"z AND aa -> ac",
"dy AND ej -> el",
"bj OR bi -> bk",
"kk RSHIFT_3 -> km",
"NOT cn -> co",
"gn AND gp -> gq",
"cq AND cs -> ct",
"eo LSHIFT_15 -> es",
"lg OR lm -> ln",
"dy OR ej -> ek",
"NOT di -> dj",
"1 AND fi -> fj",
"kf LSHIFT_15 -> kj",
"NOT jy -> jz",
"NOT ft -> fu",
"fs AND fu -> fv",
"NOT hr -> hs",
"ck OR cl -> cm",
"jp RSHIFT_5 -> js",
"iv OR jb -> jc",
"is OR it -> iu",
"ld OR le -> lf",
"NOT fc -> fd",
"NOT dm -> dn",
"bn OR by -> bz",
"aj AND al -> am",
"cd LSHIFT_15 -> ch",
"jp AND ka -> kc",
"ci OR ct -> cu",
"gv AND gx -> gy",
"de AND dk -> dm",
"x RSHIFT_5 -> aa",
"et RSHIFT_2 -> eu",
"x RSHIFT_1 -> aq",
"ia OR ig -> ih",
"bk LSHIFT_1 -> ce",
"y OR ae -> af",
"NOT ca -> cb",
"e AND f -> h",
"ia AND ig -> ii",
"ck AND cl -> cn",
"NOT jh -> ji",
"z OR aa -> ab",
"1 AND en -> eo",
"ib AND ic -> ie",
"NOT eh -> ei",
"iy AND ja -> jb",
"NOT bb -> bc",
"ha OR gz -> hb",
"1 AND cx -> cy",
"NOT ax -> ay",
"ev OR ew -> ex",
"bn RSHIFT_2 -> bo",
"er OR es -> et",
"eu OR fa -> fb",
"jp OR ka -> kb",
"ea AND eb -> ed",
"k AND m -> n",
"et RSHIFT_3 -> ev",
"et RSHIFT_5 -> ew",
"hz RSHIFT_1 -> is",
"ki OR kj -> kk",
"NOT h -> i",
"lv LSHIFT_15 -> lz",
"as RSHIFT_1 -> bl",
"hu LSHIFT_15 -> hy",
"iw AND ix -> iz",
"lf RSHIFT_1 -> ly",
"fp OR fv -> fw",
"1 AND am -> an",
"ap LSHIFT_1 -> bj",
"u LSHIFT_1 -> ao",
"b RSHIFT_5 -> f",
"jq AND jw -> jy",
"iu RSHIFT_3 -> iw",
"ih AND ij -> ik",
"NOT iz -> ja",
"de OR dk -> dl",
"iu OR jf -> jg",
"as AND bd -> bf",
"b RSHIFT_3 -> e",
"jq OR jw -> jx",
"iv AND jb -> jd",
"cg OR ch -> ci",
"iu AND jf -> jh",
"lx -> a",
"1 AND cc -> cd",
"ly OR lz -> ma",
"NOT el -> em",
"1 AND bh -> bi",
"fb AND fd -> fe",
"lf OR lq -> lr",
"bn RSHIFT_3 -> bp",
"bn AND by -> ca",
"af AND ah -> ai",
"cf LSHIFT_1 -> cz",
"dw OR dx -> dy",
"gj AND gu -> gw",
"jg AND ji -> jj",
"jr OR js -> jt",
"bl OR bm -> bn",
"gj RSHIFT_2 -> gk",
"cj OR cp -> cq",
"gj OR gu -> gv",
"b OR n -> o",
"o AND q -> r",
"bi LSHIFT_15 -> bm",
"dy RSHIFT_1 -> er",
"cu AND cw -> cx",
"iw OR ix -> iy",
"hc OR hd -> he",
"0 -> c",
"db OR dc -> dd",
"kk RSHIFT_2 -> kl",
"eq LSHIFT_1 -> fk",
"dz OR ef -> eg",
"NOT ed -> ee",
"lw OR lv -> lx",
"fw AND fy -> fz",
"dz AND ef -> eh",
"jp RSHIFT_3 -> jr",
"lg AND lm -> lo",
"ci RSHIFT_2 -> cj",
"be AND bg -> bh",
"lc LSHIFT_1 -> lw",
"hm AND ho -> hp",
"jr AND js -> ju",
"1 AND io -> ip",
"cm AND co -> cp",
"ib OR ic -> id",
"NOT bf -> bg",
"fo RSHIFT_5 -> fr",
"ip LSHIFT_15 -> it",
"jt AND jv -> jw",
"jc AND je -> jf",
"du OR dt -> dv",
"NOT fx -> fy",
"aw AND ay -> az",
"ge LSHIFT_15 -> gi",
"NOT ak -> al",
"fm OR fn -> fo",
"ff AND fh -> fi",
"ci RSHIFT_5 -> cl",
"cz OR cy -> da",
"NOT ey -> ez",
"NOT ju -> jv",
"NOT ls -> lt",
"kk AND kv -> kx",
"NOT ii -> ij",
"kl AND kr -> kt",
"jk LSHIFT_15 -> jo",
"e OR f -> g",
"NOT bs -> bt",
"hi AND hk -> hl",
"hz OR ik -> il",
"ek AND em -> en",
"ao OR an -> ap",
"dv LSHIFT_1 -> ep",
"an LSHIFT_15 -> ar",
"fo RSHIFT_1 -> gh",
"NOT im -> in",
"kk RSHIFT_1 -> ld",
"hw LSHIFT_1 -> iq",
"ec AND ee -> ef",
"hb LSHIFT_1 -> hv",
"kb AND kd -> ke",
"x AND ai -> ak",
"dd AND do -> dq",
"aq OR ar -> as",
"iq OR ip -> ir",
"dl AND dn -> do",
"iu RSHIFT_5 -> ix",
"as OR bd -> be",
"NOT go -> gp",
"fk OR fj -> fl",
"jm LSHIFT_1 -> kg",
"NOT cv -> cw",
"dp AND dr -> ds",
"dt LSHIFT_15 -> dx",
"et RSHIFT_1 -> fm",
"dy RSHIFT_3 -> ea",
"fp AND fv -> fx",
"NOT p -> q",
"dd RSHIFT_2 -> de",
"eu AND fa -> fc",
"ba AND bc -> bd",
"dh AND dj -> dk",
"lr AND lt -> lu",
"he RSHIFT_1 -> hx",
"ex AND ez -> fa",
"df OR dg -> dh",
"fj LSHIFT_15 -> fn",
"NOT kx -> ky",
"gk OR gq -> gr",
"dy RSHIFT_2 -> dz",
"gh OR gi -> gj",
"lj AND ll -> lm",
"x OR ai -> aj",
"bz AND cb -> cc",
"1 AND lu -> lv",
"as RSHIFT_3 -> au",
"ce OR cd -> cf",
"il AND in -> io",
"dd RSHIFT_1 -> dw",
"NOT lo -> lp",
"c LSHIFT_1 -> t",
"dd RSHIFT_3 -> df",
"dd RSHIFT_5 -> dg",
"lh AND li -> lk",
"lf RSHIFT_5 -> li",
"dy RSHIFT_5 -> eb",
"NOT kt -> ku",
"at OR az -> ba",
"x RSHIFT_3 -> z",
"NOT lk -> ll",
"lb OR la -> lc",
"1 AND r -> s",
"lh OR li -> lj",
"ln AND lp -> lq",
"kk RSHIFT_5 -> kn",
"ea OR eb -> ec",
"ci AND ct -> cv",
"b RSHIFT_2 -> d",
"jp RSHIFT_1 -> ki",
"NOT cr -> cs",
"NOT jd -> je",
"jp RSHIFT_2 -> jq",
"jn OR jo -> jp",
"lf RSHIFT_3 -> lh",
"1 AND ds -> dt",
"lf AND lq -> ls",
"la LSHIFT_15 -> le",
"NOT fg -> fh",
"at AND az -> bb",
"au AND av -> ax",
"kw AND ky -> kz",
"v OR w -> x",
"kk OR kv -> kw",
"ks AND ku -> kv",
"kh LSHIFT_1 -> lb",
"1 AND kz -> la",
"NOT kc -> kd",
"x RSHIFT_2 -> y",
"et OR fe -> ff",
"et AND fe -> fg",
"NOT ac -> ad",
"jl OR jk -> jm",
"1 AND jj -> jk",
"bn RSHIFT_1 -> cg",
"NOT kp -> kq",
"ci RSHIFT_3 -> ck",
"ev AND ew -> ey",
"1 AND ke -> kf",
"cj AND cp -> cr",
"ir LSHIFT_1 -> jl",
"NOT gw -> gx",
"as RSHIFT_2 -> at",
"iu RSHIFT_1 -> jn",
"cy LSHIFT_15 -> dc",
"hg OR hh -> hi",
"ci RSHIFT_1 -> db",
"au OR av -> aw",
"km AND kn -> kp",
"gj RSHIFT_1 -> hc",
"iu RSHIFT_2 -> iv",
"ab AND ad -> ae",
"da LSHIFT_1 -> du",
"NOT bw -> bx",
"km OR kn -> ko",
"ko AND kq -> kr",
"bv AND bx -> by",
"kl OR kr -> ks",
"1 AND ht -> hu",
"df AND dg -> di",
"NOT ag -> ah",
"d OR j -> k",
"d AND j -> l",
"b AND n -> p",
"gf OR ge -> gg",
"gg LSHIFT_1 -> ha",
"bn RSHIFT_5 -> bq",
"bo OR bu -> bv",
"1 AND gy -> gz",
"s LSHIFT_15 -> w",
"NOT ie -> if",
"as RSHIFT_5 -> av",
"bo AND bu -> bw",
"hz AND ik -> im",
"bp AND bq -> bs",
"b RSHIFT_1 -> v",
"NOT l -> m",
"bp OR bq -> br",
"g AND i -> j",
"br AND bt -> bu",
"t OR s -> u",
"hz RSHIFT_5 -> ic",
"gk AND gq -> gs",
"fl LSHIFT_1 -> gf",
"he RSHIFT_3 -> hg",
"gz LSHIFT_15 -> hd",
"hf OR hl -> hm",
"1 AND gd -> ge",
"fo OR fz -> ga",
"id AND if -> ig",
"fo AND fz -> gb",
"gr AND gt -> gu",
"he OR hp -> hq",
"fq AND fr -> ft",
"ga AND gc -> gd",
"fo RSHIFT_2 -> fp",
"gl OR gm -> gn",
"hg AND hh -> hj",
"NOT hn -> ho",
"gl AND gm -> go",
"he RSHIFT_5 -> hh",
"NOT gb -> gc",
"hq AND hs -> ht",
"hz RSHIFT_3 -> ib",
"hz RSHIFT_2 -> ia",
"fq OR fr -> fs",
"hx OR hy -> hz",
"he AND hp -> hr",
"gj RSHIFT_5 -> gm",
"hf AND hl -> hn",
"hv OR hu -> hw",
"NOT hj -> hk",
"gj RSHIFT_3 -> gl",
"fo RSHIFT_3 -> fq",
"he RSHIFT_2 -> hf"
]

main(inputString)
main(inputString2)
