#!/usr/bin/python

import re

def main(inputData):
   two = 0
   three = 0
   for s in inputData:
      double = []
      tripple = []
      for c in s:
         if c not in double:
            if len(re.findall(c, s)) == 2:
               double.append(c)
         if c not in tripple:
            if len(re.findall(c, s)) == 3:
               tripple.append(c)
      #print double, tripple
      if len(double) > 0:
         two += 1
      if len(tripple) > 0:
         three += 1
   print 'Twos: {} Threes: {} Res1: {}'.format(two, three, two*three)
   for i in range(len(inputData)-1):
      for j in range(i+1, len(inputData)):
         diff = len(inputData[i])
         newWord = []
         for c in range(len(inputData[i])):
            if inputData[i][c] == inputData[j][c]:
               diff -= 1
               newWord.append(inputData[i][c])
         if diff == 1:
            print 'Res2: {}'.format(''.join(newWord))

inputData = [
   'abcdef',
   'bababc',
   'abbcde',
   'abcccd',
   'aabcdd',
   'abcdee',
   'ababab',
]

inputData = [
   'mgdsdwqulhrinkatfjoyzxcbvq',
   'megsdwpulhrinkasfjdyzxcbvk',
   'megsdwpulhmibkatfjoyzccbvq',
   'megsdwtuohrinkatfjoyzecbvq',
   'megsdwpulhdinkatfyoyzxcbvb',
   'megszwpulhrirkatfjoyexcbvq',
   'eegsdwpulhzinkatfjoyzxdbvq',
   'megsdwpulhginkatfjoyqucbvq',
   'leqsdwpulhrinkatfeoyzxcbvq',
   'megsdwpblhrandatfjoyzxcbvq',
   'megrdwpudhrinvatfjoyzxcbvq',
   'mlgsdwpulhrinkatfuoyzxcbyq',
   'mensdwpunhrinsatfjoyzxcbvq',
   'megsdwpnlhrinqatfjoyzxcbuq',
   'megsdwpnlhrinkatfqoysxcbvq',
   'megsdwpulhrinkjtfjoywxobvq',
   'megsdwpclhbinkaffjoyzxcbvq',
   'mersdwpulhrinkattjoyzxcbdq',
   'megsddpwohrinkatfjoyzxcbvq',
   'mejsdwpulhrinratfjoyzxcbvl',
   'megsdwpujhrinkatfjkbzxcbvq',
   'megsdwpujhrinkatfjoyircbvq',
   'megsdwgulhrinkatojoyzxcbvm',
   'qegsdwpulhrinkatfjoyzxggvq',
   'megsdwpflhrinkatfjsazxcbvq',
   'megsdwpulhridkagfjoyzzcbvq',
   'mejsdwpulhriykatfjoyyxcbvq',
   'measdwpulhriakatfjoyzacbvq',
   'mebsdwpulhrinkatfjoyzxmyvq',
   'megsdwpflnrinkatfjoyzxcbxq',
   'megsdwpulhxinuatfjoytxcbvq',
   'megsdwsflhrinkatfjoyzxcmvq',
   'megsdwpuuhritkarfjoyzxcbvq',
   'megsdwpulhrinkazfjoyexcjvq',
   'megsdwpulhrifkatfjokzxcbvc',
   'megsdwmulvrinkatfjoyzxcblq',
   'meggdwpulhrfnkatfjoybxcbvq',
   'megsdwptlhrindatyjoyzxcbvq',
   'megsdwpulhrinkauqjoyzxibvq',
   'megsdwddlhrifkatfjoyzxcbvq',
   'megddwpulhrinkagfjoyzxcbva',
   'messdupulhrinkatfjoyzxqbvq',
   'megsdwpuahrinkatfjotzxchvq',
   'megsewpulhrankathjoyzxcbvq',
   'megsdwpulhrinkatfjoynqcbvv',
   'megsdwpulhrifkatfjotzxcbtq',
   'megsdjpulcrinkitfjoyzxcbvq',
   'fefsowpulhrinkatfjoyzxcbvq',
   'megsdwpulapinkatfjoyzvcbvq',
   'mejsdwpularinkatfjonzxcbvq',
   'megsxwpllrrinkatfjoyzxcbvq',
   'megsdlpulxvinkatfjoyzxcbvq',
   'megsdwpulhriekztfjoyzxxbvq',
   'megspwpulhrinuatfjoyzxcgvq',
   'megqdwpulhrinkatfjoyzujbvq',
   'megsdtpuehrinkatfjoyzxtbvq',
   'megsdwjulhrmnmatfjoyzxcbvq',
   'megjdwpulhrinkztfjoyzpcbvq',
   'megsdwpuljrinkawfjlyzxcbvq',
   'mewsdwpulhtinkatfjodzxcbvq',
   'megsdwpulhrinkatfcoizxcmvq',
   'meisdwpulhrinkatawoyzxcbvq',
   'megshwpulhrinkatfjoyzxcbtz',
   'megsdwpulhfinkatfjowzxcbvj',
   'megodwpulhrcskatfjoyzxcbvq',
   'megydxpulhrinkatfjofzxcbvq',
   'megsdwpulhrinkatljoytxdbvq',
   'mwgsdwpulyrinkatfjoyzxvbvq',
   'meesdwpulhrinkatfjcwzxcbvq',
   'cegsdwpwlhrinkatfioyzxcbvq',
   'megsdwpulhrinkatfqhyxxcbvq',
   'megsrrpulhrxnkatfjoyzxcbvq',
   'megsdgpulhrinkatfjoypxcbnq',
   'xegsdwpulhrinkaxkjoyzxcbvq',
   'mngsdwpulhrenkatfjofzxcbvq',
   'mecsdwpulhrinkabfjoozxcbvq',
   'pegsdkpulhrinkatfuoyzxcbvq',
   'megpdwpughrinkatfjoyzxzbvq',
   'mxgrdwpulhrinyatfjoyzxcbvq',
   'megsdwpulhpigkatfjoyzxcbfq',
   'mhgsdwpulhrinkagfjoxzxcbvq',
   'megsdwpblhtinkatfjqyzxcbvq',
   'megsawvulhrinkatfjoyzxcfvq',
   'metsuwpulhrinkatfjowzxcbvq',
   'mexsdwpulhrinkatsjoyzxvbvq',
   'megtdwpulhrinkatfjoizxcpvq',
   'megidwpjlhrinkatfdoyzxcbvq',
   'megsdwpuljrivkatfjoyqxcbvq',
   'mespdppulhrinkatfjoyzxcbvq',
   'megsdcpulhminkatftoyzxcbvq',
   'megsdwpulhriskatfjayzlcbvq',
   'mejsdwpulhrinkatfvoyzxibvq',
   'megfdwputhriykatfjoyzxcbvq',
   'megsdwparhrinkbtfjoyzxcbvq',
   'mtgsdwpulhmingatfjoyzxcbvq',
   'megsdwjulhrinkatfjtyzxtbvq',
   'megsvwpulhrinkatfjoyzecbvf',
   'megsdwpulprinkatyqoyzxcbvq',
   'zegsdwpulhwinkatfjoyzxcfvq',
   'megsdwiulhrinkatfjoyzxcjcq',
   'aegsdwpulirinkatfjoyvxcbvq',
   'mepsdwculbrinkatfjoyzxcbvq',
   'msgsdcpulhrinkctfjoyzxcbvq',
   'megsdwpulhrinkatfjoozxfevq',
   'megscwpulhrinkatmjoyzxcbsq',
   'megsdwpulhrinkltfjoyzxtmvq',
   'megsddpulhrixkatfjyyzxcbvq',
   'megsdwpulhrinkctfjoqzhcbvq',
   'megsbapblhrinkatfjoyzxcbvq',
   'megsdwpulhrinkatfjoyyxgpvq',
   'mwpsdwpulhrinkutfjoyzxcbvq',
   'megsdwpulhrinvnlfjoyzxcbvq',
   'megsdwsulorinkakfjoyzxcbvq',
   'mbgsdwpulhrinkktfjoyzxcbvg',
   'megddwpulhrindatfjoyzxcbvr',
   'memsdwpulhrinkatqjoyzxcbvo',
   'megsdwpulbrinkarfjoyzxcbxq',
   'megsdwpulhrilkatfjoynxcgvq',
   'mxgsdzpulhrinkatfjoydxcbvq',
   'megsawpulhrinkotfjoyzacbvq',
   'measdwpulhrinkctvjoyzxcbvq',
   'medsdwpulhtinkaqfjoyzxcbvq',
   'megsdwsulhrknkatfjoylxcbvq',
   'megadwpulhrinkatfjkyzxcbvh',
   'mygsdwpulhrinkatfboyzxcavq',
   'megsdwpulhrinkaufjxyzccbvq',
   'mtgsdwpulhrunkatfkoyzxcbvq',
   'megsdwpulhrinkamfwryzxcbvq',
   'meesdwpulhrgnkatnjoyzxcbvq',
   'megddwpolhrinkatfjoyixcbvq',
   'megsdwpulhrinsatfjoyzicwvq',
   'mmgsdwpulhrinkltfjoyzxcgvq',
   'meisdwpulhhinkatfjoyzxubvq',
   'megpdwpulhrinkatfroyzxcbkq',
   'megszwpuhhrinkatfjoyzxcbzq',
   'mersdwpulhrikcatfjoyzxcbvq',
   'mjgsdwpulhrinratfjoyzxcbvl',
   'megsdwnulkxinkatfjoyzxcbvq',
   'megsdwpulhrinkatlaoyzxpbvq',
   'megsdwpulhribkitfjjyzxcbvq',
   'megsdwpzlhrinkalfjoyzkcbvq',
   'megsdwpulhrinkutfjoyzxcdnq',
   'mfgpdwputhrinkatfjoyzxcbvq',
   'oegshwpclhrinkatfjoyzxcbvq',
   'megvdwxulhrinkatfjowzxcbvq',
   'mrgydwpulhrinkatfjoyzxcbvl',
   'megsdwpuqhrinkaxfjoyzxcbfq',
   'megsdwpughrinixtfjoyzxcbvq',
   'megsdwpslxrinkatfjoyzxcbvl',
   'megsdwpukhrinkatfjovzxnbvq',
   'megsdwpulnrinkrtojoyzxcbvq',
   'megsdwpuvhrinkatfjjyzxclvq',
   'vegrdwpulhrinzatfjoyzxcbvq',
   'melsdwwulvrinkatfjoyzxcbvq',
   'megsdwpulhrizkbtfjoyzjcbvq',
   'megsdwpulhrinlatfjoyzkcbvr',
   'megsdweulhrinkaofqoyzxcbvq',
   'megsdcpulhrifkatfdoyzxcbvq',
   'negsdwpulhainkztfjoyzxcbvq',
   'megsdwpklhrinkttfjoyzxvbvq',
   'megsdwpothrdnkatfjoyzxcbvq',
   'megsdwpulvrinkatfaoyzxcbvr',
   'mewsdwpulhrinkatfooyzxtbvq',
   'megtdwpulhrinkatfxoyzxcbvy',
   'zegsdwpulhrinkamljoyzxcbvq',
   'mkgodwpulhrcnkatfjoyzxcbvq',
   'megsdepularinkatfjoyzxybvq',
   'segsdwpulhrinkatfmoyzycbvq',
   'mbgsdwpulhrsnkztfjoyzxcbvq',
   'megsdwpmlhrinkatfjxyzhcbvq',
   'megsdwpulhrinkatfboyqxmbvq',
   'megsdwpulhrinkadtpoyzxcbvq',
   'megsdmpulhrjnkatfjoyzxwbvq',
   'megsdwpulhrivkatfroywxcbvq',
   'megsdwdulhrinkatpjwyzxcbvq',
   'megsdwpylhrdrkatfjoyzxcbvq',
   'megsdwpulhrvnkptfjoyzlcbvq',
   'megsdwpuihridkatfjuyzxcbvq',
   'megsdwpulhbiikatfjxyzxcbvq',
   'meggdwpulurinkatfjoyaxcbvq',
   'mehsnwpulcrinkatfjoyzxcbvq',
   'megsdwpulhrinkatfjoczdclvq',
   'megsdwjulhrinkatfhkyzxcbvq',
   'megsdwpulhrinoatfjoyzxcwvy',
   'megpdwpelhrfnkatfjoyzxcbvq',
   'megsjwpulhrwnkatfjdyzxcbvq',
   'megsdwpulhrbniatfjoyzxcbpq',
   'megsdwpulhrwnkatfjoydxcpvq',
   'megsdwrulhrinkatfjvyixcbvq',
   'yegvdwpulhtinkatfjoyzxcbvq',
   'meosdwpulhrinkatfjhyzxsbvq',
   'mjgsdwpulhrinkatfjoyyxcjvq',
   'megsdwpulhrinkatfnoyzlmbvq',
   'mehsdfkulhrinkatfjoyzxcbvq',
   'megsdwpuahrinkatfyoyzxcwvq',
   'megsdwpulhyinkatfjobzkcbvq',
   'megsdwpjlhrinkatfnoyzscbvq',
   'megsdwiulhrinqatfjoyzxcavq',
   'megsdwpulurinkatfjoykxcbmq',
   'megsdwpmlhvinkatfjotzxcbvq',
   'megswwpulhrinfatfjoytxcbvq',
   'mxgsdwpulhrrnkatfjoyhxcbvq',
   'megubwpulhrinkaafjoyzxcbvq',
   'megsdwpulhrdnsztfjoyzxcbvq',
   'megsdwpulhronkgtfjhyzxcbvq',
   'megsdwzulhfinratfjoyzxcbvq',
   'megsdwpulhrinkrtfjqyixcbvq',
   'megspwpulhrinkatfjoywxcavq',
   'megmfjpulhrinkatfjoyzxcbvq',
   'lelsdwpulhrinsatfjoyzxcbvq',
   'megsdwnultrinkatfjoyzxybvq',
   'megsdwpulhdnnkatfjpyzxcbvq',
   'megsdwpulhzinkatfjoyzhcpvq',
   'megoddpulhrilkatfjoyzxcbvq',
   'megsdvpulhrwnkatfjoyzxcbdq',
   'megsdwpulhmikkatfjoyzxcbvr',
   'meesdwpulhrinkaofjoazxcbvq',
   'megndwhulhrinfatfjoyzxcbvq',
   'megsdwpulhjihkatfjoyzxcbvb',
   'jegsdwpulhrinkattjoszxcbvq',
   'megsdwpulhrenkatfjodzxcbvp',
   'mefsdwpulhrinkatfjoyzxcczq',
   'megsdwpulhrknkatfjovzxcbvb',
   'megytwpulhrinkatfjoyzxcbvo',
   'csgsdwpulhrinkatdjoyzxcbvq',
   'megsbwpulhrinkazfjtyzxcbvq',
   'mrgsdwpulhjinkatfjoyzxcbvm',
   'megsywzulhrinkatfjofzxcbvq',
   'megxdwpulhrndkatfjoyzxcbvq',
   'mcgsdwpuphrixkatfjoyzxcbvq',
   'megsdlpulxvinkatfvoyzxcbvq',
   'megsdwpulhrinfatfjoyzicbvo',
   'megwgwpulhrinpatfjoyzxcbvq',
   'mggsdwpulhrinkatfjtrzxcbvq',
   'msgsdwpulirinkatfjoyzxcbaq',
   'megsdwpulhrineatfeoyzxcbvl',
   'megsdnpulhrinkatojoyzxcbvb',
   'mfgsdwpulhdinkatmjoyzxcbvq',
   'megsdwpulhrinkawfjuyzxcbvg',
   'megsdwpulhrincatfjoyzxcxvu',
   'mevsdwzplhrinkatfjoyzxcbvq',
   'megskweulhfinkatfjoyzxcbvq',
   'mebsdvpulhrinkatfjoyzxcbkq',
   'megddwiulhrinkatfioyzxcbvq',
   'mygsdwpulhqinkatfooyzxcbvq',
   'megsdweulhrfnkatfjoybxcbvq',
   'mrgsdhpulmrinkatfjoyzxcbvq',
   'megsdwkukhrinkatftoyzxcbvq',
   'megsqwpulhrinfatfjoyzxebvq',
   'megsdwpulhriskanfjoyzxctvq',
]

main(inputData)
